#include "dbconfig.hpp"
#include <iostream>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <windows.h>

using namespace std;

string DatabaseConfig::getConnectionString() const {
    stringstream ss;
    ss << "dbname=" << dbname
       << " user=" << user
       << " password=" << password
       << " host=" << host
       << " port=" << port;
    return ss.str();
}

bool DatabaseConfig::loadFromFile(const string& filename) {
    ifstream file(filename);
    if (!file.is_open()) {
        cerr << "Cannot open config file: " << filename << endl;
        return false;
    }
    
    string line;
    while (getline(file, line)) {
        // Пропускаем комментарии и пустые строки
        if (line.empty() || line[0] == '#') {
            continue;
        }
        
        // Ищем знак равенства
        size_t equalsPos = line.find('=');
        if (equalsPos == string::npos) {
            continue;
        }
        
        string key = line.substr(0, equalsPos);
        string value = line.substr(equalsPos + 1);
        
        // Убираем пробелы
        key.erase(0, key.find_first_not_of(" \t"));
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t") + 1);
        
        // Заполняем соответствующие поля
        if (key == "host") host = value;
        else if (key == "port") port = value;
        else if (key == "dbname") dbname = value;
        else if (key == "user") user = value;
        else if (key == "password") password = value;
        else if (key == "charset") charset = value;
        else if (key == "timezone") timezone = value;
    }
    
    file.close();
    return true;
}

bool DatabaseConfig::saveToFile(const string& filename) const {
    ofstream file(filename);
    if (!file.is_open()) {
        cerr << "Cannot create config file: " << filename << endl;
        return false;
    }
    
    file << "# PostgreSQL Database Configuration" << endl;
    file << "# Generated by PqxxProject" << endl << endl;
    
    file << "host=" << host << endl;
    file << "port=" << port << endl;
    file << "dbname=" << dbname << endl;
    file << "user=" << user << endl;
    file << "password=" << password << endl;
    file << "charset=" << charset << endl;
    file << "timezone=" << timezone << endl;
    
    file.close();
    return true;
}

void DatabaseConfig::editInteractive() {
    SetConsoleOutputCP(1251);
    SetConsoleCP(1251);
    
    cout << "\n=== Database Configuration Editor ===" << endl;
    cout << "Leave field empty to keep current value." << endl << endl;
    
    string input;
    
    cout << "Host [" << host << "]: ";
    getline(cin, input);
    if (!input.empty()) host = input;
    
    cout << "Port [" << port << "]: ";
    getline(cin, input);
    if (!input.empty()) port = input;
    
    cout << "Database name [" << dbname << "]: ";
    getline(cin, input);
    if (!input.empty()) dbname = input;
    
    cout << "Username [" << user << "]: ";
    getline(cin, input);
    if (!input.empty()) user = input;
    
    cout << "Password [" << string(password.length(), '*') << "]: ";
    getline(cin, input);
    if (!input.empty()) password = input;
    
    cout << "Charset [" << charset << "]: ";
    getline(cin, input);
    if (!input.empty()) charset = input;
    
    cout << "Timezone [" << timezone << "]: ";
    getline(cin, input);
    if (!input.empty()) timezone = input;
    
    cout << "\nConfiguration updated." << endl;
}